services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: supallama-ai-web-workers-fastapi-web
    # '/start.sh' is the command to start fastapi inside container
    command: /start-fastapi.sh
    # This volume is used to map the files and folders on
    # the host to the docker container. 
    # This way, if we change code on the host, the code in 
    # the docker container will also be changed. 
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env/.dev-env
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
